//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Episource.KeePass.EKF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EpiSource.KeePass.Ekf.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string AnyUI_ButtonAbort {
            get {
                return ResourceManager.GetString("AnyUI.ButtonAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string AnyUI_ButtonCancel {
            get {
                return ResourceManager.GetString("AnyUI.ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AnyUI_ButtonOK {
            get {
                return ResourceManager.GetString("AnyUI.ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_ButtonExport {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.ButtonExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate random key.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_ButtonGenerateRandomKey {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.ButtonGenerateRandomKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import key file.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_ButtonImportKey {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.ButtonImportKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select active key file.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_ButtonSelectActiveDbKeyFile {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.ButtonSelectActiveDbKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☑ Change.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_ColumnChange {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.ColumnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_ColumnProvider {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.ColumnProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial#.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_ColumnSerial {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.ColumnSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_ColumnSubject {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.ColumnSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write key file:  {0}.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_DialogTextFailureExportingKey {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.DialogTextFailureExportingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_DialogTextFileNotFound {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.DialogTextFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected (plain) key file is invalid..
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_DialogTextInvalidPlainKeyFile {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.DialogTextInvalidPlainKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected key file is not a valid Keypass XML Key File. Do you want to use the file as (plain) key file anyway?.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_DialogTextNoXmlKeyFile {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.DialogTextNoXmlKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Failure.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_DialogTitleFailureExportingKey {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.DialogTitleFailureExportingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File  not found.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_DialogTitleFileNotFound {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.DialogTitleFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key file.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_DialogTitleInvalidPlainKeyFile {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.DialogTitleInvalidPlainKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import key file.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_DialogTitleNoXmlKeyFile {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.DialogTitleNoXmlKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_KeyActionAuthorize {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.KeyActionAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_KeyActionNoChange {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.KeyActionNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_KeyActionUnauthorize {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.KeyActionUnauthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Key file of active database).
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_KeySourceActiveDb {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.KeySourceActiveDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_KeySourceImported {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.KeySourceImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Randomly generated key).
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_KeySourceRandom {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.KeySourceRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Unknown key data).
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_KeySourceUnknown {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.KeySourceUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database:.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_LabelDatabase {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.LabelDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Source:.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_LabelKeySource {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.LabelKeySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbprint: {0}.
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_LabelThumbprint {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.LabelThumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key must be exported before use. Please store safely..
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_ValidationMessageKeyNeedsExport {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.ValidationMessageKeyNeedsExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No smartcard found..
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_ValidationMessageNoSmartcard {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.ValidationMessageNoSmartcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one smart card..
        /// </summary>
        internal static string EditEncryptedKeyFileDialog_ValidationMessageSelectSmartcard {
            get {
                return ResourceManager.GetString("EditEncryptedKeyFileDialog.ValidationMessageSelectSmartcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown / EKF.
        /// </summary>
        internal static string KeyPairModel_KeyProvider_EkfAuthorizationList {
            get {
                return ResourceManager.GetString("KeyPairModel.KeyProvider.EkfAuthorizationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HBCI / RDH Card.
        /// </summary>
        internal static string KeyPairModel_KeyProvider_HbciRdhCard {
            get {
                return ResourceManager.GetString("KeyPairModel.KeyProvider.HbciRdhCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenPGP Card.
        /// </summary>
        internal static string KeyPairModel_KeyProvider_OpenPGP {
            get {
                return ResourceManager.GetString("KeyPairModel.KeyProvider.OpenPGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIV / Windows.
        /// </summary>
        internal static string KeyPairModel_KeyProvider_Piv {
            get {
                return ResourceManager.GetString("KeyPairModel.KeyProvider.Piv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string KeyPairModel_UnknownKeyProvider {
            get {
                return ResourceManager.GetString("KeyPairModel.UnknownKeyProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN blocked permanently. Use PUK to recover..
        /// </summary>
        internal static string PinBlockedDialog_DialogText {
            get {
                return ResourceManager.GetString("PinBlockedDialog.DialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN blocked.
        /// </summary>
        internal static string PinBlockedDialog_DialogTitle {
            get {
                return ResourceManager.GetString("PinBlockedDialog.DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeePass requests access to private key:
        ///
        ///{0}.
        /// </summary>
        internal static string NativeSmartcardUI_ContextTest {
            get {
                return ResourceManager.GetString("NativeSmartcardUI.ContextTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Encrypted Key File.
        /// </summary>
        internal static string SmartcardEncryptedKeyProvider_ButtonEditKeyFile {
            get {
                return ResourceManager.GetString("SmartcardEncryptedKeyProvider.ButtonEditKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to locate encrypted key file. Are you sure, this KeePass database has been setup for use with the {0}?.
        /// </summary>
        internal static string SmartcardEncryptedKeyProvider_DialogTextEkfNotFound {
            get {
                return ResourceManager.GetString("SmartcardEncryptedKeyProvider.DialogTextEkfNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} operation was denied by the system&apos;s virus scanner (false positive). Consider whitelisting `{1}`..
        /// </summary>
        internal static string SmartcardEncryptedKeyProvider_DialogTextUnblockerDeniedByVirusScanner {
            get {
                return ResourceManager.GetString("SmartcardEncryptedKeyProvider.DialogTextUnblockerDeniedByVirusScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please unlock your smartcard..
        /// </summary>
        internal static string SmartcardOperationDialog_DialogHeading {
            get {
                return ResourceManager.GetString("SmartcardOperationDialog.DialogHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Among others, this may require entering a PIN or pressing a button. Details depend on the type of smartcard and reader you are using..
        /// </summary>
        internal static string SmartcardOperationDialog_DialogText {
            get {
                return ResourceManager.GetString("SmartcardOperationDialog.DialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for smartcard....
        /// </summary>
        internal static string SmartcardOperationDialog_DialogTitle {
            get {
                return ResourceManager.GetString("SmartcardOperationDialog.DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        internal static string SmartcardRequiredDialog_ColumnProvider {
            get {
                return ResourceManager.GetString("SmartcardRequiredDialog.ColumnProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☑ Ready.
        /// </summary>
        internal static string SmartcardRequiredDialog_ColumnReady {
            get {
                return ResourceManager.GetString("SmartcardRequiredDialog.ColumnReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial#.
        /// </summary>
        internal static string SmartcardRequiredDialog_ColumnSerial {
            get {
                return ResourceManager.GetString("SmartcardRequiredDialog.ColumnSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string SmartcardRequiredDialog_ColumnSubject {
            get {
                return ResourceManager.GetString("SmartcardRequiredDialog.ColumnSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert and select a smartcard from the list below..
        /// </summary>
        internal static string SmartcardRequiredDialog_DialogText {
            get {
                return ResourceManager.GetString("SmartcardRequiredDialog.DialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smartcard required.
        /// </summary>
        internal static string SmartcardRequiredDialog_DialogTitle {
            get {
                return ResourceManager.GetString("SmartcardRequiredDialog.DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connected.
        /// </summary>
        internal static string SmartcardRequiredDialog_KeyStateConnected {
            get {
                return ResourceManager.GetString("SmartcardRequiredDialog.KeyStateConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not connected.
        /// </summary>
        internal static string SmartcardRequiredDialog_KeyStateNotConnected {
            get {
                return ResourceManager.GetString("SmartcardRequiredDialog.KeyStateNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbprint: {0}.
        /// </summary>
        internal static string SmartcardRequiredDialog_LabelThumbprint {
            get {
                return ResourceManager.GetString("SmartcardRequiredDialog.LabelThumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Wrong PIN entered..
        /// </summary>
        internal static string WrongPinDialog_DialogText {
            get {
                return ResourceManager.GetString("WrongPinDialog.DialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong PIN.
        /// </summary>
        internal static string WrongPinDialog_DialogTitle {
            get {
                return ResourceManager.GetString("WrongPinDialog.DialogTitle", resourceCulture);
            }
        }
    }
}
